export const capabilities = [
  {
    title: "Analytics & data",
    icon: "01",
    description: "Analysis, dashboards, KPIs, data quality, and repeatable processing workflows.",
    tools: ["SQL", "Python", "Power BI", "Excel", "Pandas", "R"],
  },
  {
    title: "Machine learning & statistics",
    icon: "02",
    description: "Classification, forecasting, recommenders, evaluation, regression, and econometrics.",
    tools: ["Scikit-learn", "Forecasting", "Classification", "Statistics", "Econometrics"],
  },
  {
    title: "Applied AI & automation",
    icon: "03",
    description: "Practical workflows with LLMs, embeddings, vector search, and Python automation.",
    tools: ["LLMs", "Embeddings", "Qdrant", "Vector search", "Automation"],
  },
  {
    title: "Software & collaboration",
    icon: "04",
    description: "Git, GitHub, algorithms, object-oriented programming, C#, and clear team collaboration.",
    tools: ["Git", "GitHub", "Algorithms", "OOP", "C#", "Teamwork"],
  },
];

export const experience = [
  {
    period: "2025 - Present",
    role: "Data Specialist",
    organization: "Check Point Software",
    logo: "assets/organizations/checkpoint.svg",
    summary: "I work with enterprise data to make reporting clearer, improve data reliability, and help teams make informed decisions.",
    details: [
      "Analyze structured datasets with SQL, Python, Excel, and Power BI to answer business questions and generate practical insights.",
      "Build dashboards and recurring reports that track KPIs, surface trends, and improve visibility into operational performance.",
      "Investigate data-quality issues, trace their root causes, reconcile inconsistencies, and strengthen the accuracy and reliability of reporting.",
      "Use Python automation and AI-assisted tools to simplify repetitive workflows, reduce manual effort, and make day-to-day processes more efficient.",
    ],
    tags: ["SQL", "Python", "Power BI", "Data Quality", "Automation"],
  },
  {
    period: "2024",
    role: "AI Engineer Intern",
    organization: "Checkmarx / CodeMatch",
    logo: "assets/organizations/checkmarx.svg",
    summary: "I developed CodeMatch, an applied-AI system designed to identify semantic similarity between code snippets beyond simple text matching.",
    details: [
      "Developed an LLM-based code-similarity workflow using embeddings and vector search to represent and compare the meaning of source code.",
      "Built data-retrieval workflows and benchmark datasets used to evaluate model quality, compare results, and guide performance improvements.",
      "Worked with structured datasets, databases, embedding pipelines, and Qdrant to store and retrieve code representations efficiently.",
      "Reviewed system outputs, identified performance gaps, and used data-driven adjustments to improve the reliability of the results.",
    ],
    tags: ["LLMs", "Embeddings", "Qdrant", "Evaluation", "Python"],
  },
  {
    period: "2018 - 2021",
    role: "Arrow Interception Team Leader",
    organization: "Israeli Air Force",
    logo: "assets/organizations/israeli-air-force.svg",
    summary: "I led an eight-member technical team responsible for the readiness of mission-critical defense systems in a demanding operational environment.",
    details: [
      "Oversaw the monitoring, maintenance, and operational readiness of complex technical systems where accuracy, discipline, and dependable execution were essential.",
      "Coordinated the work of an eight-member team and helped maintain a clear, responsible approach during routine activity and time-sensitive situations.",
      "The role strengthened my leadership, technical problem-solving, communication, and ability to stay focused while working with high-responsibility systems.",
    ],
    tags: ["Leadership", "Technical Operations", "Team Coordination"],
  },
];

export const projects = [
  {
    title: "CodeMatch",
    period: "Feb - Dec 2024",
    category: "ai",
    image: "assets/projects/codematch.webp",
    imageFit: "contain",
    imageBackground: "#ffffff",
    url: "https://github.com/codematch-llm",
    description: "AI-driven semantic code similarity using LLM embeddings, vector search, and benchmark datasets to detect matching code beyond surface syntax.",
    tags: ["LLMs", "Embeddings", "Vector Search", "FastAPI"],
    outcome: "Semantic code intelligence",
    featured: true,
  },
  {
    title: "Uber ESB Demand Prediction",
    period: "Feb - Oct 2024",
    category: "machine-learning",
    image: "assets/projects/uber-demand.webp",
    url: "https://github.com/YuvalBakirov/uber-esb-demand-prediction",
    description: "Time-series demand forecasting near the Empire State Building using weather, events, time, and location features; CatBoost achieved the lowest RMSE.",
    tags: ["Forecasting", "CatBoost", "Python", "Big Data"],
    outcome: "Demand forecasting",
    featured: true,
  },
  {
    title: "Music Recommendation System",
    period: "Dec 2023 - Apr 2024",
    category: "machine-learning",
    image: "assets/projects/music-recommendation.webp",
    url: "https://github.com/YuvalBakirov/music-recommendation-system",
    description: "Personalized top-10 song recommendations from 2M+ interactions using collaborative filtering, content-based methods, and matrix factorization.",
    tags: ["Recommenders", "Python", "SQL", "Evaluation"],
    outcome: "2M+ interactions",
    featured: true,
  },
  {
    title: "Boston Airbnb Analysis",
    period: "Feb - Aug 2024",
    category: "analytics",
    image: "assets/projects/boston-airbnb.webp",
    url: "https://github.com/YuvalBakirov/boston-airbnb-analysis",
    description: "Market analysis of pricing, occupancy, neighborhoods, host behavior, and revenue efficiency using RevPAN and statistical insight.",
    tags: ["R", "EDA", "Visualization", "Business Analytics"],
    outcome: "Market intelligence",
  },
  {
    title: "Image Processing",
    period: "Feb - Oct 2024",
    category: "software",
    image: "assets/projects/image-processing.webp",
    imageFit: "contain",
    imageBackground: "#ffffff",
    url: "https://github.com/YuvalBakirov/image-processing",
    description: "Python and OpenCV implementations of noise reduction, filtering, geometric transformations, histogram analysis, and feature extraction.",
    tags: ["Python", "OpenCV", "Computer Vision", "Algorithms"],
    outcome: "Visual computing",
  },
  {
    title: "US-China Trade War Seminar",
    period: "May - Dec 2024",
    category: "analytics",
    image: "assets/projects/trade-war.webp",
    url: "https://www.linkedin.com/in/yuval-bakirov/details/projects/",
    description: "Economics seminar examining how US tariffs on Chinese products during 2018-2019 affected the American economy.",
    tags: ["Economics", "Microeconomics", "Research", "Policy Analysis"],
    outcome: "Economic research",
  },
  {
    title: "TV Dialogue Classification",
    period: "Oct - Dec 2023",
    category: "machine-learning",
    image: "assets/projects/tv-dialogue.webp",
    imageFit: "contain",
    imageBackground: "#20278b",
    url: "https://github.com/YuvalBakirov/tv-show-dialogue-classification",
    description: "NLP and deep-learning workflows for classifying dialogue from Friends and Seinfeld, including preprocessing and model comparison.",
    tags: ["NLP", "Deep Learning", "CNN", "Text Classification"],
    outcome: "Dialogue NLP",
  },
  {
    title: "Bicycle Rental Demand",
    period: "Oct - Nov 2023",
    category: "machine-learning",
    image: "assets/projects/bicycle-demand.webp",
    url: "https://github.com/YuvalBakirov/bicycle-rental-demand-prediction",
    description: "Daily rental-demand prediction from weather, temperature, season, and time features using optimized ensemble regression models.",
    tags: ["XGBoost", "CatBoost", "Feature Engineering", "Regression"],
    outcome: "Mobility forecasting",
  },
  {
    title: "Sweden Education Reform",
    period: "Feb - Oct 2023",
    category: "analytics",
    image: "assets/projects/econometrics.webp",
    imageFit: "contain",
    imageBackground: "#0a5b91",
    url: "https://github.com/YuvalBakirov/econometrics-analysis",
    description: "Difference-in-differences study of Sweden's 1940s education reform and its effect on schooling and labor-market earnings.",
    tags: ["Econometrics", "R", "Causal Analysis", "Regression"],
    outcome: "Policy evaluation",
  },
  {
    title: "Malicious File Classification",
    period: "Feb - Aug 2023",
    category: "machine-learning",
    image: "assets/projects/malicious-file.webp",
    url: "https://github.com/YuvalBakirov/malicious-file-classification",
    description: "Binary-classification pipeline using static file features, exploratory analysis, feature preparation, model training, and reliability evaluation.",
    tags: ["Classification", "Pandas", "Random Forest", "EDA"],
    outcome: "Security analytics",
  },
  {
    title: "Happiness Data Analysis",
    period: "Feb - Sep 2022",
    category: "analytics",
    image: "assets/projects/happiness.webp",
    url: "https://github.com/YuvalBakirov/happiness-data-analysis-project",
    description: "Statistical analysis of World Happiness Report indicators including GDP, life expectancy, freedom, hypothesis testing, and regression.",
    tags: ["Statistics", "Hypothesis Testing", "R", "Visualization"],
    outcome: "Global indicators",
  },
  {
    title: "Bubble Trouble",
    period: "Oct 2017 - May 2018",
    category: "software",
    image: "assets/projects/bubble-trouble.webp",
    imageFit: "contain",
    imageBackground: "#858786",
    url: "https://github.com/YuvalBakirov/bubble-trouble",
    description: "Two-dimensional C# game using MonoGame and XNA with OOP design, dynamic obstacles, power-ups, and AI-driven bot behavior.",
    tags: ["C#", "MonoGame", "OOP", "Game AI"],
    outcome: "Game development",
  },
];

export const education = [
  {
    years: "2021 - 2024",
    title: "B.Sc. in Digital Sciences and Economics",
    school: "Tel Aviv University",
    logo: "assets/organizations/tel-aviv-university.png",
    achievement: "2024 Dean's List",
    note: "A degree that combined quantitative technology studies with economics and business-oriented problem solving.",
    details: [
      "Coursework included data science, machine learning, SQL and databases, data analysis, statistics, algorithms, programming, and economics.",
      "Built a strong foundation in statistical modeling and economic analysis while learning to connect technical results with real business and policy questions.",
      "Applied the material through projects in forecasting, recommendation systems, NLP, econometrics, security classification, and large-scale data analysis.",
    ],
  },
  {
    years: "2017 - 2018",
    title: "Diploma in Software Engineering",
    school: "Hakfar Hayarok College",
    logo: "assets/organizations/hakfar-hayarok.png",
    achievement: "Graduated with honors",
    note: "Built my early software-engineering foundation through programming, algorithms, and object-oriented development.",
    details: [
      "Developed practical experience in C#, object-oriented programming, application structure, debugging, and turning requirements into working software.",
      "Completed the Bubble Trouble game project with MonoGame and XNA, combining gameplay logic, dynamic obstacles, power-ups, and bot behavior.",
      "This training continues to support the way I approach data and AI work: with attention to structure, maintainability, and reliable implementation.",
    ],
  },
  {
    years: "2015 - 2017",
    title: "Matriculation Certificate, Computer Science and Physics",
    school: "Ephraim Katzir High School, Holon",
    logo: "assets/organizations/ephraim-katzir.png",
    achievement: "Graduated with honors / Matriculation average: 112",
    note: "An advanced academic track that established my interest in analytical thinking, technology, and problem solving.",
    details: [
      "Majored in Computer Science at the 10-unit level and Physics at the 5-unit level.",
      "Completed advanced Mathematics and English at the 5-unit level.",
      "Graduated with honors and a matriculation average of 112.",
    ],
  },
];

export const certifications = [
  {
    logo: "assets/certifications/google.png",
    title: "Google AI Essentials Specialization",
    issuer: "Google",
    issued: "Issued June 2026",
    description: "Practical training in using generative AI responsibly and effectively, including prompting, evaluating outputs, and incorporating AI tools into everyday research, writing, analysis, and productivity workflows.",
  },
  {
    logo: "assets/certifications/aws-wordmark.png",
    title: "AWS Academy Cloud Developing",
    issuer: "Amazon Web Services",
    issued: "Issued March 2024",
    description: "Hands-on cloud-development training covering the foundations of building applications with AWS services, working with cloud resources, and understanding the security, deployment, and architectural considerations of cloud-based solutions.",
  },
  {
    logo: "assets/certifications/microsoft.png",
    title: "Microsoft Certified: Azure AI Fundamentals",
    issuer: "Microsoft",
    issued: "Issued October 2023 / Credential ID F4BAC2D190C921AB",
    description: "Validates foundational knowledge of AI and machine-learning concepts, common AI workloads, responsible AI principles, and the role of Microsoft Azure services in building AI solutions.",
  },
];
