export const capabilities = [
  { title: "Analytics & BI", items: "SQL / Power BI / Excel / KPI reporting" },
  { title: "Machine Learning", items: "Classification / Forecasting / Recommenders" },
  { title: "Data Engineering", items: "Python / Pandas / NumPy / Validation" },
  { title: "AI & Automation", items: "LLMs / Embeddings / Vector search / Workflows" },
];

export const experience = [
  {
    period: "2025 - Present",
    role: "Data Specialist",
    organization: "Check Point Software",
    logo: "assets/organizations/checkpoint.svg",
    summary: "Enterprise analytics, dashboards, KPI reporting, data-quality investigation, and Python/AI automation.",
    tags: ["SQL", "Python", "Power BI", "Data Quality", "Automation"],
  },
  {
    period: "2024",
    role: "AI Engineer Intern",
    organization: "Checkmarx / CodeMatch",
    logo: "assets/organizations/checkmarx.svg",
    summary: "Built and evaluated an LLM-based semantic code-similarity system using embeddings, benchmark datasets, and vector search.",
    tags: ["LLMs", "Embeddings", "Qdrant", "Evaluation", "Python"],
  },
  {
    period: "2018 - 2021",
    role: "Arrow Interception Team Leader",
    organization: "Israeli Air Force",
    logo: "assets/organizations/israeli-air-force.svg",
    summary: "Led an eight-member technical team supporting mission-critical system readiness.",
    tags: ["Leadership", "Technical Operations", "Team Coordination"],
  },
];

export const projects = [
  {
    title: "CodeMatch",
    period: "Feb - Dec 2024",
    category: "ai",
    image: "assets/projects/codematch.webp",
    imageFit: "contain",
    imageBackground: "#ffffff",
    url: "https://github.com/codematch-llm",
    description: "AI-driven semantic code similarity using LLM embeddings, vector search, and benchmark datasets to detect matching code beyond surface syntax.",
    tags: ["LLMs", "Embeddings", "Vector Search", "FastAPI"],
    outcome: "Semantic code intelligence",
    featured: true,
  },
  {
    title: "Uber ESB Demand Prediction",
    period: "Feb - Oct 2024",
    category: "machine-learning",
    image: "assets/projects/uber-demand.webp",
    url: "https://github.com/YuvalBakirov/uber-esb-demand-prediction",
    description: "Time-series demand forecasting near the Empire State Building using weather, events, time, and location features; CatBoost achieved the lowest RMSE.",
    tags: ["Forecasting", "CatBoost", "Python", "Big Data"],
    outcome: "Demand forecasting",
    featured: true,
  },
  {
    title: "Music Recommendation System",
    period: "Dec 2023 - Apr 2024",
    category: "machine-learning",
    image: "assets/projects/music-recommendation.webp",
    url: "https://github.com/YuvalBakirov/music-recommendation-system",
    description: "Personalized top-10 song recommendations from 2M+ interactions using collaborative filtering, content-based methods, and matrix factorization.",
    tags: ["Recommenders", "Python", "SQL", "Evaluation"],
    outcome: "2M+ interactions",
    featured: true,
  },
  {
    title: "Boston Airbnb Analysis",
    period: "Feb - Aug 2024",
    category: "analytics",
    image: "assets/projects/boston-airbnb.webp",
    url: "https://github.com/YuvalBakirov/boston-airbnb-analysis",
    description: "Market analysis of pricing, occupancy, neighborhoods, host behavior, and revenue efficiency using RevPAN and statistical insight.",
    tags: ["R", "EDA", "Visualization", "Business Analytics"],
    outcome: "Market intelligence",
  },
  {
    title: "Image Processing",
    period: "Feb - Oct 2024",
    category: "software",
    image: "assets/projects/image-processing.webp",
    imageFit: "contain",
    imageBackground: "#ffffff",
    url: "https://github.com/YuvalBakirov/image-processing",
    description: "Python and OpenCV implementations of noise reduction, filtering, geometric transformations, histogram analysis, and feature extraction.",
    tags: ["Python", "OpenCV", "Computer Vision", "Algorithms"],
    outcome: "Visual computing",
  },
  {
    title: "US-China Trade War Seminar",
    period: "May - Dec 2024",
    category: "analytics",
    image: "assets/projects/trade-war.webp",
    url: "https://www.linkedin.com/in/yuval-bakirov/details/projects/",
    description: "Economics seminar examining how US tariffs on Chinese products during 2018-2019 affected the American economy.",
    tags: ["Economics", "Microeconomics", "Research", "Policy Analysis"],
    outcome: "Economic research",
  },
  {
    title: "TV Dialogue Classification",
    period: "Oct - Dec 2023",
    category: "machine-learning",
    image: "assets/projects/tv-dialogue.webp",
    imageFit: "contain",
    imageBackground: "#20278b",
    url: "https://github.com/YuvalBakirov/tv-show-dialogue-classification",
    description: "NLP and deep-learning workflows for classifying dialogue from Friends and Seinfeld, including preprocessing and model comparison.",
    tags: ["NLP", "Deep Learning", "CNN", "Text Classification"],
    outcome: "Dialogue NLP",
  },
  {
    title: "Bicycle Rental Demand",
    period: "Oct - Nov 2023",
    category: "machine-learning",
    image: "assets/projects/bicycle-demand.webp",
    url: "https://github.com/YuvalBakirov/bicycle-rental-demand-prediction",
    description: "Daily rental-demand prediction from weather, temperature, season, and time features using optimized ensemble regression models.",
    tags: ["XGBoost", "CatBoost", "Feature Engineering", "Regression"],
    outcome: "Mobility forecasting",
  },
  {
    title: "Sweden Education Reform",
    period: "Feb - Oct 2023",
    category: "analytics",
    image: "assets/projects/econometrics.webp",
    imageFit: "contain",
    imageBackground: "#0a5b91",
    url: "https://github.com/YuvalBakirov/econometrics-analysis",
    description: "Difference-in-differences study of Sweden's 1940s education reform and its effect on schooling and labor-market earnings.",
    tags: ["Econometrics", "R", "Causal Analysis", "Regression"],
    outcome: "Policy evaluation",
  },
  {
    title: "Malicious File Classification",
    period: "Feb - Aug 2023",
    category: "machine-learning",
    image: "assets/projects/malicious-file.webp",
    url: "https://github.com/YuvalBakirov/malicious-file-classification",
    description: "Binary-classification pipeline using static file features, exploratory analysis, feature preparation, model training, and reliability evaluation.",
    tags: ["Classification", "Pandas", "Random Forest", "EDA"],
    outcome: "Security analytics",
  },
  {
    title: "Happiness Data Analysis",
    period: "Feb - Sep 2022",
    category: "analytics",
    image: "assets/projects/happiness.webp",
    url: "https://github.com/YuvalBakirov/happiness-data-analysis-project",
    description: "Statistical analysis of World Happiness Report indicators including GDP, life expectancy, freedom, hypothesis testing, and regression.",
    tags: ["Statistics", "Hypothesis Testing", "R", "Visualization"],
    outcome: "Global indicators",
  },
  {
    title: "Bubble Trouble",
    period: "Oct 2017 - May 2018",
    category: "software",
    image: "assets/projects/bubble-trouble.webp",
    imageFit: "contain",
    imageBackground: "#858786",
    url: "https://github.com/YuvalBakirov/bubble-trouble",
    description: "Two-dimensional C# game using MonoGame and XNA with OOP design, dynamic obstacles, power-ups, and AI-driven bot behavior.",
    tags: ["C#", "MonoGame", "OOP", "Game AI"],
    outcome: "Game development",
  },
];

export const education = [
  {
    years: "2021 - 2024",
    title: "B.Sc. in Digital Sciences and Economics",
    school: "Tel Aviv University",
    logo: "assets/organizations/tel-aviv-university.jpg",
    note: "2024 Dean's List / Data science, machine learning, statistics, databases, algorithms, economics, and business-oriented problem solving.",
  },
  {
    years: "2017 - 2018",
    title: "Diploma in Software Engineering",
    school: "Hakfar Hayarok College",
    logo: "assets/organizations/hakfar-hayarok.png",
    note: "Graduated with honors / Software engineering foundations and object-oriented development.",
  },
  {
    years: "2015 - 2017",
    title: "Matriculation Certificate, Computer Science and Physics",
    school: "Ephraim Katzir High School, Holon",
    logo: "assets/organizations/ephraim-katzir.png",
    note: "Graduated with honors with a matriculation average of 112. Majored in Computer Science (10 units) and Physics (5 units), with advanced English and Mathematics (5 units each).",
  },
];

export const certifications = [
  { logo: "assets/certifications/google.png", title: "Google AI Essentials Specialization", issuer: "Google", issued: "Issued June 2026" },
  { logo: "assets/certifications/aws-wordmark.png", title: "AWS Academy Cloud Developing", issuer: "Amazon Web Services", issued: "Issued March 2024" },
  { logo: "assets/certifications/microsoft.png", title: "Microsoft Certified: Azure AI Fundamentals", issuer: "Microsoft", issued: "Issued October 2023 / Credential ID F4BAC2D190C921AB" },
];
